language: minimal

dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'deb https://packages.cloudfoundry.org/debian stable main'
        key_url: 'https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key'
    packages:
      - cf-cli
services:
  - docker

jobs:
  include:
  - name: "Build & Deploy Helm"
    script:
      - docker run -v $TRAVIS_BUILD_DIR/deployment/helm/:/helm  -w /helm --entrypoint /helm/build.sh alpine/helm:3.0.0-beta.5 $TRAVIS_TAG
    deploy:
      - provider: releases
        draft: true
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
        api_key:
          secure: nsO30W4L2lK2HTqL9NyfLd9xkYgJ5MIWtCs9mh2/h7q0g06vzQnG7QUXTp9x57VCkMe6KVphdP4Yq+Ys9j3bQ3AKQ7tVmK4TT9WtLowLPNCwdIXi7HvifXA21hbnfB2Uv2Tp8DdCnmRniI0T4YCojLNu1PwtXXCYVWSxtVGP955yLldT9JVEVXu6SbMCYFqwJ85+m2tnsGs6ynwFt4iHiiGkDC3KfA8z0kDS8suHSXZrMvppJhSN93fPAJZfV5vj4M535m0cQZYdnN6yxIV8b97wq9kWwruINVrjaZhdE8rLC4Xr2BnBhrvhMjPZbs1mknEKtw396eySD/ggyy0xdtw/KApfMvzjc9whu5JdBtGvYW9wfZgZ2HFkawyO82ZC8lpuS3oisgL6LtqZmLxgJhc1waMqKVk3ILWuXVGezGK7usVgDspcBkOMQc5oZKdUeiamOFtoOqzmQ35/+7rlp3tVQz6MmS04HSp0QEnxJEO9d9ppS55jZ4WKSKwlS5MY3LqH2/B5tEyKw/hldXcWfQliMKHWBjp3t7NJ+E7Cy3Pym4YAIQhP/AeqCP++ctM2G9VhFfYbtzYRMiZQg7Yb/Yq1Q7elQJKpvzpifcSIfY59mEMiHy6Yj6YUfwQ69EM7aaJvaOF+XPsC2ef89+gSxyShR8RqXxKtH0/ocDrw0IU=
        file_glob: true
        file:
        - $TRAVIS_BUILD_DIR/deployment/helm/postfacto-*.tgz